### ISSUE TITLE
Create summary files with numbers of MAR residential units

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/MAR#15]
Use active_res_occupancy_count from MAR.Address_points_????_?? data set.

**Comment by ptatian** [comment]
What I meant here was create standard summary files for ward, neighborhood cluster, etc.

**Comment by lhendey** [comment]
Yes, I figured. Perhaps as part of the Large units study...

**Comment by lhendey** [comment]
@rpitingolo  = this would be helpful to do for large units analysis. can we fit this in?

@ptatian - it would be good to merge on ui_proptype in this summary process?

**Comment by ptatian** [comment]
@lhendey Yes, merging ui_proptype would be worth a try. Total residential units for sure, and then separate vars for units that can be classified into single family, condo, multifamily rental, coop.

**Comment by rpitingolo** [comment]
@lhendey I'll see if I can assign this out so we can use it for large units.

**Comment by lhendey** [comment]
@ptatian  = i was going to assign to yipeng-  it doesn't seem like this is exactly parallel to num_units_all? I didn't see any entry and exit dates for the addresses? should we just do a summary that reflects current point in time? Assuming we'd not want to overwrite the files and would save each version? (or that's not necessary because we could go back to the point file?)

**Comment by ptatian** [comment]
@lhendey Yes, MAR is just a snapshot, but it may include "retired" addresses. I think that it needs to be a point in time count based on the date when the data were pulled. Saving versions as a time series would definitely be valuable.

**Comment by lhendey** [comment]
@maggiesu0725  - let me know when you have time to work on this issue - we can talk through the steps.

cc @rpitingolo

**Comment by lhendey** [comment]
@rpitingolo - can you read through this chain? This one would be worth starting for sure.

**Comment by rpitingolo** [comment]
@lhendey will do.

**Comment by rpitingolo** [comment]
@lhendey most of our summary files are longitudinal. Does it make sense to do that for this one too? If so, I assume we would use the newest addres MAR.Address_points_????_?? for each year. What do you think?

**Comment by rpitingolo** [comment]
L:\Libraries\MAR\Prog\MAR_summary_units.log

Closing this issue in order to set up the initial summary files. I will open a new issue to add the 2019 data.
