### ISSUE TITLE
Correct errors on Address_points_view.sas

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/MAR#31]

**Comment by rpitingolo** [comment]
@ptatian it looks like a view won't work with %finalize_data_set. Here's the error I'm seeing:
ERROR: [Finalize_data_set] Input data set ADDRESS_POINTS_VIEW does not exist.

Even though it looks like the view was define correctly. Should this program use Mar.Address_points_view in the proc sql statement instead?

**Comment by ptatian** [comment]
@rpitingolo No, _%Finalize_data_set()_ will not work with views. That's why it originally used the _%Dc_update_meta_file()_ macro instead. You should [restore that code](https://github.com/NeighborhoodInfoDC/MAR/commit/adabcb4a3a7afb7e20ccb8dc9d4c96722aa15113#diff-7dbd0c2abd1418eb665d9208e903c0ea).

**Comment by rpitingolo** [comment]
@ptatian OK. Thanks.
